#%RAML 1.0 NamedExample
value:
  [ 
   {
                id: 1234565,
                title: "inventory",
                content: "counting",
                createdAt: "2024-10-09T15:30:00Z",
                updatedAt: "2024-10-09T15:30:00Z"
    },
    {
                id: 1234565,
                title: "inventory",
                content: "counting",
                createdAt: "2024-10-09T15:30:00Z",
                updatedAt: "2024-10-09T15:30:00Z"
    }
  ]  